### ISSUE TITLE
Allow users to opt in to downloading the songs instead of streaming

### ISSUE THREAD

**Issue by Saad-Alareqi** [OMGDuke/SDH-GameThemeMusic#27]
Hi,
As the title says. The music will play after 5 to 10 seconds and that's in my opinion isn't practical. 
So my suggestion is to make your plugin download the music first time the user opens the game page in background. In this case the music will play instantly next times and also this will make the music also play when offline.

**Comment by OMGDuke** [comment]
5 to 10 seconds is much longer than I tend to see but that may have something to do with physical location/network speed.

The current way of getting the audio isn't perfect and it's something I'm improving upon here https://github.com/OMGDuke/SDH-GameThemeMusic/issues/23

In terms of downloads It's something I'm considering but it will have to come after some of the other tasks I'm working on

**Comment by Saad-Alareqi** [comment]
It's not necessary to allow the user to download or make it visible to the user. You can cache the music in a hidden folder and make the plugin play the cached music offline if its available. I use the steam deck a lot while I'm out and without an internet connection, and I miss the music playing in background while offline.

**Comment by syberphunk** [comment]
I keep going back and forth thinking about the download option.

Allowing downloads from youtube opens up to copyright problems.

Though yt-dlp exists, which can pull the audio streams.
