### ISSUE TITLE
Stop audio loader bgm when playing game music

### ISSUE THREAD

**Issue by OMGDuke** [OMGDuke/SDH-GameThemeMusic#3]

**Comment by beebls** [comment]
Hey, Audio Loader developer here. Audio Loader has been mostly in maintenance mode as I haven't had much time to work on it, if you do want to implement this I could give you some advice on how audioloader music works, however like I said I don't have tons of time nowadays so I'm not sure how involved I can be.

We just use a normal <audio> element, so I'm sure theres some way that can be exported and play/paused

**Comment by GoldenReverie** [comment]
To further what Beebis put on this https://github.com/EMERALD0874/SDH-AudioLoader/releases/tag/v1.5.0 see their latest release . To quote: "AudioLoader now exposes window.AUDIOLOADER_MENUMUSIC" This should allow the ability to disable the music on the Audio Loader Plugin when yours has commenced.

**Comment by OkamiTakahashi** [comment]
Yeah this would be a handy feature, I actually had to tune down my Audio Loader sound of choice just to enjoy game theme music.

**Comment by SteelSavant** [comment]
@OMGDuke I've made a PR that should resolve this -- it plays nicely on my system, but if you have any issues, ping me.

**Comment by ZazaMastro** [comment]
> @OMGDuke I've made a PR that should resolve this -- it plays nicely on my system, but if you have any issues, ping me.

Sorry could you provide your build please?

**Comment by OMGDuke** [comment]
Thanks a lot @SteelSavant I'm away from home at the moment but will give it a test when I'm back in a few days!
