### ISSUE TITLE
Allow to start in the middle of the theme 

### ISSUE THREAD

**Issue by DSigmund** [OMGDuke/SDH-GameThemeMusic#32]
Many theme songs start slow, especially modern ones.

An idea could be a simple trigger to start like one minute In the theme.

I saw an issue already that asks to allow to have the user set a time, which I think is great for known themes.

But on a casual scroll I want a sensible default starting Point.

Or maybe save the user settings from above on a server and allow an option to use this community settings.

I could help write and host such a simple server, if you like...

**Comment by OMGDuke** [comment]
In terms of starting at different times: https://github.com/OMGDuke/SDH-GameThemeMusic/issues/22

A game music database is out of scope for this plugin. But if someone builds it I'm sure it could take advantage of it in the future!
