### ISSUE TITLE
Manual search results disappear 

### ISSUE THREAD

**Issue by sonatamartica** [OMGDuke/SDH-GameThemeMusic#34]
When choosing a song to overwrite the default option, searching shows a lot of results then they disappear and can't be selected. Why is this? I cannot choose the song I want before it vanishes from the result screen.

**Comment by OMGDuke** [comment]
This is due to how the results are currently fetched. Youtube encrypts some of the audio streams so some are fetchable.

This issue will be solved by this task https://github.com/OMGDuke/SDH-GameThemeMusic/issues/23

**Comment by OMGDuke** [comment]
Closing this issue, please refer to #23 for future updates
