### ISSUE TITLE
Identify Artist, Album, Track name and Source

### ISSUE THREAD

**Issue by Zodiaksl** [OMGDuke/SDH-GameThemeMusic#46]
Hello,

I play alot of Indie games. I enjoy using your plugin and I've been playing alot of Army of Ruin lately. It's a small indie developer and I've noticed that when I'm about to launch it, it finds a great song with Vocals that has nothing to do with the song.

I've tried identifying the song with my phone and it can't find anything and I can't find anything using google for army of ruin vocals or song.

Can someone please help me out and also possibly add these features in the future?

Thank you :)

**Comment by OMGDuke** [comment]
Try going to change theme music from the context menu. You should be able to see what's currently selected
