### ISSUE TITLE
"Change Theme Music" option keeps disappearing.

### ISSUE THREAD

**Issue by GraalOtonami** [OMGDuke/SDH-GameThemeMusic#47]
See title.
Every time I open the game options to change the theme, I see the option for a split second before it disappears. This was a occasional issue on the previous OS version, but the update has exacerbated the issue so I can't access it anymore.

**Comment by OMGDuke** [comment]
It's due to how the audio is is loaded via scraping

I have a fix in the works that can be tracked here https://github.com/OMGDuke/SDH-GameThemeMusic/issues/23

**Comment by Anti-Apple4life** [comment]
I am still having this issue in December 2023
