### ISSUE TITLE
The "Default Muted" option should give you the choice to turn it off for all games or just for Non-Steam

### ISSUE THREAD

**Issue by pontifex91** [OMGDuke/SDH-GameThemeMusic#49]
The "Default muted" option turned on disables music for all games, but I believe the user should have the choice of muting music for all games or only Non-Steam games.

I like to have music turned on by default, but only in Steam games, because there is a minimal chance of an error here. And in Non-Steam games, when I add Setup.exe, Launcher.exe, Game.exe and any other exe (at the moment when I'm just setting up the game, before I'm sure that the game works fine and you can rename it and add a cover), I often hear just some random video from YouTube, with conversations or squeals of streamers.

**Comment by OMGDuke** [comment]
Sorry I don't currently have any plans to implement this.
