### ISSUE TITLE
Main/Popular soundtracks don't appear through search

### ISSUE THREAD

**Issue by Jackoberto** [OMGDuke/SDH-GameThemeMusic#50]
Sometimes the videos/soundtracks I'm looking for don't show up or only show up for a split second only to disappear

For example the main menu theme for [Life Is Strange True Colors](https://youtu.be/YIqXnirQlvM) and this popular video for [Cyberpunk 2077](https://youtu.be/cIto6qzW0Mc) show up at first then disappear immediately

**Comment by OkamiTakahashi** [comment]
I've had this issue too! I wanted Suspect for Holocure, and the Theme to Dangeresque II from the Strong Bad Sings album (for both Holocure and the two Dangeresque games from Videlectrix in my library), but they vanish before I can select them! I've had to settle for a lousy Siivagunner Rip and Coach Z singing the Dangeresque theme himself!

**Comment by OMGDuke** [comment]
Closing this in favour of #23 Please refer to that issue for updates
