### ISSUE TITLE
All copyrighted tracks and label uploads are blocked

### ISSUE THREAD

**Issue by AlenaEK** [OMGDuke/SDH-GameThemeMusic#51]
Some games have copyrighted main themes. Some games have the best quality uploads be the label copies. BB's Theme from Death Stranding is blocked despite not being copyrighted. Please fix this or add the ability to play files since it reduces our enjoyment of your plugin.

**Comment by Kyr4l** [comment]
Many game songs are copyrighted, leaving mostly irrelevant results

**Comment by ZazaMastro** [comment]
Definitively something to fix. The plugin is great, but this limitation is non sense.

**Comment by OMGDuke** [comment]
Search is currently done by scraping YouTube. It's unreliable and I have another solution that I'm looking into that I believe will resolve this. #23

**Comment by OMGDuke** [comment]
Closing this in favour of #23 Please refer to that issue for updates
