### ISSUE TITLE
Allow users to define the URL with a text box

### ISSUE THREAD

**Issue by GraalOtonami** [OMGDuke/SDH-GameThemeMusic#62]
Some videos appear for a split second before disappearing.
If I could put a video URL directly into the system, it'd allow me to get the exact video without relying on the limited search.

**Comment by OMGDuke** [comment]
Have you tried v 1.5.0 on the testing store? It should fix the videos disappearing issue.

**Comment by GraalOtonami** [comment]
Thank you! I wasn't aware there was a testing channel!
