### ISSUE TITLE
Plugin causing deck to say "something went wrong displaying this content..." Over everything, even the plugin menu itself so I can't even update if there is one

### ISSUE THREAD

**Issue by SLURMPHeroOfTime** [OMGDuke/SDH-GameThemeMusic#64]
Something went wrong error everywhere. As soon as I install this plugin my steam deck has this displayed everywhere to the point I can't even access the plugin menu to potentially update.

**Comment by OMGDuke** [comment]
What system update channel?
What decky update channel?
What version of the plugin?

**Comment by DrLegitamate** [comment]
I am also having this problem.

Stable system channel
Stable decky channel
Version 1.5.0

**Comment by OMGDuke** [comment]
> I am also having this problem.
> 
> Stable system channel Stable decky channel Version 1.5.0

I've got Stable system, stable decky and v1.5.0 working here.

If you haven't already give your deck a quick restart

**Comment by SLURMPHeroOfTime** [comment]
> I am also having this problem.
> 
> Stable system channel Stable decky channel Version 1.5.0

I'm on stable OS. I'm on most recent version of decky loader and 1.4.1-1 of game theme music I believe. I think it was a decky loader issue now because I saw people having the same error with CSS loader as well. But for some reason it seems to have fixed itself? It's working fine now

**Comment by OMGDuke** [comment]
Closing this issue 👍
