### ISSUE TITLE
Plugin makes the screen flash or bug out for a few seconds rather than smoothly transition to a loading animation when I click to play a game. Could this be fixed please?

### ISSUE THREAD

**Issue by Warrior-Wanderer** [OMGDuke/SDH-GameThemeMusic#65]
I appreciate the recent update to coincide with the new Steam update. However, I noticed that when I confirm to play a game, the screen jitters about for a few seconds before the game begins proper.

I am dead certain it's the plugin causing the issue as when I delete it, the screen transitions to the loading animation normally and smoothly. I also made sure to delete the other plugins and just use GTM and the issue persists.

Could someone (perhaps the person/people behind the plugin) fix this issue please? I know it must be annoying as it was just updated, but it'd be great if this is addressed.

**Comment by Khrouhman** [comment]
Hello i am having this issue as well. Its not a deal break by itself but when docked and using the TV is gets really bad

**Comment by OMGDuke** [comment]
Fixed in #75
