### ISSUE TITLE
Piped Instance unselectable in Steam game recording beta.

### ISSUE THREAD

**Issue by Memenado** [OMGDuke/SDH-GameThemeMusic#68]
Plugin can be installed and viewed totally fine on newest beta, but the piped instance option is greyed out and unable to be selected.

**Comment by AchillesPDX** [comment]
Yep. Same issue here. Latest beta has broken things again. Wish Valve would just add official plugin support of some kind.

**Comment by OMGDuke** [comment]
Fixed in #77
