### ISSUE TITLE
List populates a ton of available songs initially, but then they all disappear leaving no music options on every U.S.A. Piped Instance (and others)

### ISSUE THREAD

**Issue by ThisByzantineConduit** [OMGDuke/SDH-GameThemeMusic#71]
This has been happening for a while, but I've been able to circumvent it by choosing an alternate Piped Instance until now. For years this plugin worked flawlessly but now the default/official international Piped Instance and all alternative U.S.A. Piped Instances, and many from other regions, populate a big list of songs which then completely disappears leaving no music options. 

This is consistent no matter how generalized my search terms are. Any idea on a fix? Tried reinstalling the plugin to no avail.

**Comment by OMGDuke** [comment]
Fixed in #77
