### ISSUE TITLE
Plugin is completely broken, all music options disappear regardless of "piped instance"

### ISSUE THREAD

**Issue by TheDefectiveButcher** [OMGDuke/SDH-GameThemeMusic#72]
As the title suggests, this plugin just doesn't work. I'd also like to request that we remove the previously stringent restrictions on what songs stay in the list. It's kinda stupid.

**Comment by realkorja** [comment]
I hope this plugin makes a comeback or someone else does it. This thing was critical to my menu browsing experience

**Comment by Darksk0pe** [comment]
Please fix it , i need this so much 😘

**Comment by TheDefectiveButcher** [comment]
They should make it so that you can use files that you have locally for when you're offline. This and removing the restriction on copyright content. It IS pretty annoying when your favorite game has copyright music so nothing loads.

**Comment by ThisByzantineConduit** [comment]
Seconded. What's odd is this was initially a slow "breaking", as this exact behavior would occur but could be fixed by switching Piped Instances, but now not a single one works.

Really a bummer and hope there's a fix soon as this is my favorite Decky plugin 🤞.

**Comment by ThisByzantineConduit** [comment]
> They should make it so that you can use files that you have locally for when you're offline. This and removing the restriction on copyright content. It IS pretty annoying when your favorite game has copyright music so nothing loads.

The suggestion for an offline music files option is such a good idea. Love being able to search music and switch songs on the fly while online, but for times when the internet is spotty or the plugin breaks this would be amazing.

Would love to see this feature implemented!

**Comment by OMGDuke** [comment]
Fixed in #77
