### ISSUE TITLE
plugin is entirely broken

### ISSUE THREAD

**Issue by realkorja** [OMGDuke/SDH-GameThemeMusic#73]
Entries from YouTube will populated after search, and then all listed entries disappear instantly. Songs can no longer selected. Occasionally the program manages to select automatically.

**Comment by ThisByzantineConduit** [comment]
Seconded. What's odd is this was initially a slow "breaking", as this exact behavior would occur but could be fixed by switching Piped Instances, but now not a single one works.

Really a bummer and hope there's a fix soon as this is my favorite Decky plugin 🤞.

**Comment by OMGDuke** [comment]
Fixed in #77
