### ISSUE TITLE
Plug-in is Broken

### ISSUE THREAD

**Issue by murdocksblock** [OMGDuke/SDH-GameThemeMusic#74]
Everything shows up for a second then disappears regardless of the instance.

**Comment by Novabella** [comment]
I'm getting the same issue. The few times I could select a song, it still just wouldn't play.

**Comment by ThisByzantineConduit** [comment]
Seconded. What's odd is this was initially a slow "breaking", as this exact behavior would occur but could be fixed by switching Piped Instances, but now not a single one works.

Really a bummer and hope there's a fix soon as this is my favorite Decky plugin 🤞.
