### ISSUE TITLE
No way to select music

### ISSUE THREAD

**Issue by matsumurae** [OMGDuke/SDH-GameThemeMusic#78]
After the update of SteamOS and breaking all the plugins, seems like this one is on the bad side.

No matter what I do: clear the search, write my own search... Nothing will let me choose a song, it just does the search, I see them and then POF! all the cards disappear one by one leaving only "no music".

Reinstalled. Uninstalled and installed again. Nothing works.

SteamOS 3.5.19
Decky 2.12.3
Game theme music 1.5.0

**Comment by OMGDuke** [comment]
Fixed in V1.6.0

Under review here https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/680

Note when it's on the testing store you'll need to be on the prerelease version of decky.
