### ISSUE TITLE
How to apply the new update to the plugin?

### ISSUE THREAD

**Issue by ThisByzantineConduit** [OMGDuke/SDH-GameThemeMusic#79]
Don't see it available in the Decky store yet and tried to manually install the new release by downloading the ZIP on the release page here, but it doesn't get recognized by DeckyLoader when extracting it to home/deck/homebrew/plugins.

Will it just take a little for Decky to start pushing put the new build/is there a way to manually install this now if I wanted to?

Thanks so much for all the hard work for the community and for the new fix!

**Comment by OMGDuke** [comment]
It's available on the testing store that you can change to in decky settings. Note that it uses the new version of decky so you'll need to be on the decky pre release channel for now
