### ISSUE TITLE
USA Individous Instances Not Working

### ISSUE THREAD

**Issue by ThisByzantineConduit** [OMGDuke/SDH-GameThemeMusic#80]
So sorry to bug you again. I get it's pre-release for a reason so that could be part of this, but I switched to both the Testing Store and Pre-Release Decky, found 1.6 and installed it, but when I select either of the two USA Individious Incidences neither works. 

One gives null results and the other just spins eternally when searching. Am I missing something/any way to fix it?

If not it's fine and I'll just go back to Stable until the build is ready to deploy there. Thanks again for all your work making the Deck a way better experience—this plugin is awesome as a VGM lover and that's why I wanna get it working again so badly 😅.

**Comment by OMGDuke** [comment]
Just tried the iv.ggtyler.dev US instance and worked fine for me.

Might be worth trying a few instances regardless of country and see which works best for you.
