### ISSUE TITLE
1.6.0 Update Not Showing on Decky Store

### ISSUE THREAD

**Issue by murdocksblock** [OMGDuke/SDH-GameThemeMusic#81]
Pretty much what the title says. I see the update here on Github but the latest available on the Decky Store is 1.5.0. 
Manually installing from Git provides errors, so have been waiting for it to be pushed to the Decky Store.

**Comment by OMGDuke** [comment]
It's on the testing store, you'll need to be on the prerelease version of decky to use it as it requires the new version of decky
