### ISSUE TITLE
Music Shows for a second then disappears

### ISSUE THREAD

**Issue by KyleStilkey** [OMGDuke/SDH-GameThemeMusic#84]
I was really hoping this new update would fix this problem but sadly it doesn't.

I'm on 1.6.0 and Decky 3.0 and I've tried all other instances and they all result in the same problem.

I can see the music all load up then a second later they all disappeare and I can't select a single one. I'm not sure why this is happening but would love to figure out why this still is. Thanks!

**Comment by richpanda1214** [comment]
I Also have the same issues.

**Comment by OMGDuke** [comment]
Invidious issue, try another instance.

I'm using the inv.nadeko.net instance and songs are working perfectly for me 👍 

Hopefully the other instances start working soon too

**Comment by KyleStilkey** [comment]
I can tell you no it's not working there is multiple complaints still on Reddit too, this is a ongoing problem, like I stated above I tried every single instance and they all do the same thing. I'm not sure why you closed these issue reports out and blame the individual user, why not take the time to figure out why this is happening to some and not others, clearly there is something wrong that's causing this for some of the users.

**Comment by Cabl3z** [comment]
I'm having this issue as well.
